// Curated names with established Chinese corporate or brand usage. Symbols not
// listed here deliberately keep their source name instead of being machine-translated.
const COMPANY_NAMES_ZH = Object.freeze({
  AAPL: '苹果公司',
  ABBV: '艾伯维',
  ABNB: '爱彼迎',
  ABT: '雅培',
  ACN: '埃森哲',
  ADI: '亚德诺半导体',
  AIG: '美国国际集团',
  AMAT: '应用材料',
  AMD: '超威半导体',
  AMGN: '安进',
  AMZN: '亚马逊',
  AON: '怡安',
  APO: '阿波罗全球管理',
  AXP: '美国运通',
  AZN: '阿斯利康',
  BA: '波音',
  BABA: '阿里巴巴',
  BAC: '美国银行',
  BDX: '碧迪医疗',
  BEKE: '贝壳找房',
  BIDU: '百度',
  BK: '纽约梅隆银行',
  BLK: '贝莱德',
  BMO: '蒙特利尔银行',
  BMY: '百时美施贵宝',
  BP: '英国石油',
  'BRK.B': '伯克希尔·哈撒韦公司',
  BSX: '波士顿科学',
  CAT: '卡特彼勒',
  CAH: '康德乐',
  C: '花旗集团',
  CB: '安达保险',
  CI: '信诺集团',
  CL: '高露洁棕榄',
  CME: '芝商所',
  CMCSA: '康卡斯特',
  CNI: '加拿大国家铁路',
  COF: '第一资本金融',
  COP: '康菲',
  COST: '开市客',
  CP: '加拿大太平洋堪萨斯城铁路',
  CRM: '赛富时',
  CSCO: '思科',
  CVS: 'CVS 健康',
  CVX: '雪佛龙',
  DD: '杜邦',
  DE: '迪尔公司',
  DEO: '帝亚吉欧',
  DHR: '丹纳赫',
  DIS: '华特迪士尼公司',
  DOW: '陶氏公司',
  EL: '雅诗兰黛',
  EMR: '艾默生',
  ERIC: '爱立信',
  ETN: '伊顿',
  F: '福特汽车',
  FDX: '联邦快递',
  GE: 'GE 航空航天',
  GD: '通用动力',
  GILD: '吉利德科学',
  GIS: '通用磨坊',
  GM: '通用汽车',
  GS: '高盛',
  GSK: '葛兰素史克',
  HCA: 'HCA 医疗',
  HD: '家得宝',
  HMC: '本田汽车',
  HON: '霍尼韦尔',
  HSBC: '汇丰控股',
  IBM: '国际商业机器公司',
  ICE: '洲际交易所',
  INFY: '印孚瑟斯',
  INTC: '英特尔',
  ISRG: '直觉外科',
  JD: '京东',
  JNJ: '强生',
  JPM: '摩根大通',
  KHC: '卡夫亨氏',
  KLAC: '科磊',
  KMB: '金佰利',
  KO: '可口可乐',
  KKR: 'KKR 集团',
  LI: '理想汽车',
  LIN: '林德',
  LLY: '礼来',
  LMT: '洛克希德·马丁',
  LOW: '劳氏公司',
  LRCX: '泛林集团',
  MA: '万事达卡',
  MCD: '麦当劳',
  MCO: '穆迪',
  MDT: '美敦力',
  MDLZ: '亿滋国际',
  MET: '大都会人寿',
  MFG: '瑞穗金融集团',
  MMM: '3M 公司',
  MMC: '威达信集团',
  MO: '奥驰亚集团',
  MRK: '默沙东',
  MS: '摩根士丹利',
  MSFT: '微软公司',
  MU: '美光科技',
  MUFG: '三菱日联金融集团',
  NEM: '纽蒙特',
  NFLX: '奈飞',
  NIO: '蔚来',
  NKE: '耐克',
  NOK: '诺基亚',
  NOC: '诺斯罗普·格鲁曼',
  NOVO_B: '诺和诺德',
  NVO: '诺和诺德',
  NVS: '诺华',
  NVDA: '英伟达',
  NTES: '网易',
  ORCL: '甲骨文公司',
  OXY: '西方石油',
  PANW: '派拓网络',
  PDD: '拼多多',
  PEP: '百事公司',
  PFE: '辉瑞',
  PG: '宝洁',
  PLD: '安博',
  PM: '菲利普莫里斯国际',
  PRU: '保德信金融',
  PYPL: '贝宝',
  QCOM: '高通',
  RACE: '法拉利',
  REGN: '再生元制药',
  RHHBY: '罗氏',
  RIO: '力拓',
  RY: '加拿大皇家银行',
  SAP: '思爱普',
  SBUX: '星巴克',
  SCHW: '嘉信理财',
  SHEL: '壳牌',
  SLB: '斯伦贝谢',
  SMFG: '三井住友金融集团',
  SNY: '赛诺菲',
  SONY: '索尼',
  SPGI: '标普全球',
  STLA: '斯特兰蒂斯',
  SYK: '史赛克',
  T: 'AT&T 公司',
  TD: '多伦多道明银行',
  TCOM: '携程集团',
  TGT: '塔吉特',
  TM: '丰田汽车',
  TMO: '赛默飞世尔科技',
  TSM: '台积电',
  TSLA: '特斯拉',
  TTE: '道达尔能源',
  TXN: '德州仪器',
  UBER: '优步',
  UBS: '瑞银集团',
  UL: '联合利华',
  UNH: '联合健康集团',
  UNP: '联合太平洋',
  UPS: '联合包裹服务',
  V: '维萨公司',
  VALE: '淡水河谷',
  VRTX: '福泰制药',
  VZ: '威瑞森通信',
  WFC: '富国银行',
  WIT: '威普罗',
  WMT: '沃尔玛',
  XOM: '埃克森美孚',
  XPEV: '小鹏汽车',
  ZTS: '硕腾',
});

function normalizeSymbol(symbol) {
  return String(symbol || '').trim().toUpperCase().replace(/[/-]/g, '.');
}

export function getChineseCompanyName(symbol) {
  return COMPANY_NAMES_ZH[normalizeSymbol(symbol)] || '';
}

export function companyNameForLocale(stock, locale) {
  if (locale === 'zh-CN') return getChineseCompanyName(stock?.symbol) || stock?.name || stock?.symbol || '';
  return stock?.name || stock?.symbol || '';
}
